Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('', include('users.urls')),
]

blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'
urlpatterns =[
#Path that leads to home page
    path('', views.index, name = 'index'),

    #Path that displays all blogs
    path('blogs', views.blogs, name='blogs'),

    #Path for a single bog
    path('blog/<int:blog_id>/', views.blog, name ='blog'),
    
    #Path to create new blog
    path('new_blog/', views.new_blog, name = 'new_blog'),

    #Path to edit blog
    path('edit_blog/<int:blog_id>/', views.edit_blog, name= 'edit_blog')
    
]

users/urls.py
from django.urls import path, include
from . import views

app_name ='users'
urlpatterns = [
    #Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    #Path for registration
    path('register/', views.register, name='register')

]

blogs/models.py
from turtle import title
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length= 200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add= True)
    owner = models.ForeignKey(User, on_delete= models.CASCADE)

    def __str__(self):
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost

class NewBlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title','text',]
        label = {'title': '', 'text':''}
        widget = {'text': forms.Textarea(attrs={'cols': 100})}

# class BlogPostForm(forms.ModelForm):
#     class Meta:
#         model = BlogPost
#         fields = ['text']
#         label = {'text': ''}
#         widget = {'text': forms.Textarea(attrs= {'cols': 100 })}


    

blogs/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from .models import BlogPost
from .forms import NewBlogForm 
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    items = BlogPost.objects.all()
    context = {'items': items}
    return render(request, 'blogs/index.html',context)


def blogs(request):
    """Show all Blogs"""
    blogs = BlogPost.objects.order_by('date_added')
    context = {'blogs':blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """ Displays a Single Blog"""
    blog = BlogPost.objects.get(id = blog_id)
    context = {'blog':blog}
    return render(request, 'blogs/blog.html', context)

@login_required
def new_blog(request):
    """Add a new Blog"""
    if request.method != 'POST':
        #No form submitted; create a blank form
        form = NewBlogForm
    else:
        #form is submitted; process data
        form = NewBlogForm(data= request.POST)
        if form.is_valid():
            new_user = form.save(commit =False)
            new_user.owner = request.user
            new_user.save()
            return redirect('blogs:blogs')
    context ={'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def edit_blog(request,blog_id):
    """Edit an existing Blog"""
    blog = BlogPost.objects.get(id = blog_id)
    if blog.owner != request.user:
        raise Http404
    if request.method != 'POST':
        #No edit made
        form = NewBlogForm(instance = blog)
    else:
        #POST data is submitted; Process data
        form = NewBlogForm(instance = blog, data= request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id)
    context = {'blog':blog, 'form':form}
    return render(request, 'blogs/edit_blog.html', context)




    
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Register a new User"""
    #if post data is not submitted; display blank registration form
    if request.method != "POST":
        form = UserCreationForm()
    else:
        #Post data is submitted; process data
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            #log the user in an and redirect user to home page
            return redirect('blogs:index')
    #Display invalid or blank registration form
    context = {'form':form}
    return render(request, 'registration/register.html', context)
        

blogs/templates/blogs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,
            shrink-to-fit = no">
        <meta name="author" content="Stephen Annor Apenkwah">
        <title>SteveBlog</title>
        <script src="https://cdn.tailwindcss.com"></script>
        
        <script>
                tailwind.config = {
                theme: {
                    extend: {
                          colors: {
                            clifford: '#da373d',
          }
        }
      }
    }
        </script>
        
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    
    </head>
    <body>
        
            <header>
              
                {% if user.is_authenticated %}
                <span><a href="{% url 'blogs:blogs' %}"> Hello, {{user.username}}.</a></span>
                {% else %}
                <a href="{% url 'users:register' %}">Register</a>
                <a href="{% url 'users:login' %}">Login</a>
                {% endif %}

                
                {% if user.is_authenticated %}
                  <a href="{% url 'blogs:index' %}">SteveBlogs</a>
                  <a href="{% url 'users:logout' %}">Logout</a>

                {% else %}
                  <a href="{% url 'blogs:index' %}">SteveBlogs</a>           
                  <a href="{% url 'users:login' %}">Sign up</a>
                {% endif %}
            </header>
        
      </body>
        <main role="main">
          
              {% block page_header %}{% endblock page_header %}
         
              {% block content %}{% endblock %}
         
      </main>

</html>

blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %}
{% block content %}
<p>
    Blog: {{blog}}
</p>
<p>
    <ul>
        <li>
            <p>{{ blog.date_added|date:'M d, Y H:1' }}</p>
            <p>{{ blog.text|linebreaks }}</p>
            <p><a href="{% url 'blogs:edit_blog' blog.id %}">Edit Blog</a></p>
        </li>
    </ul>
</p>

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}
{% block content %}
<p>Blogs:</p>
<ul>
    {% for blog in blogs %}
        <li><a href="{% url 'blogs:blog' blog.id %}">{{blog}}</a></li>
    {% empty %}
        <li>No blog has been added yet</li>
    {% endfor %}

</ul>
<a href="{% url 'blogs:new_blog' %}">Add new blog </a>

{% endblock content %}

blogs/templates/blogs/edit_blog.html
{% extends 'blogs/base.html '%}
{% block content %}
    <p><a href="{% url 'blogs:blog' blog.id %}">{{blog}}</a></p>

    <p>Edit Blog:</p>
    <form action="{% url 'blogs:edit_blog' blog.id %}" method= 'post'>
        {% csrf_token %}
        {{ form.as_p}}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
     
{% endblock page_header %}

{% block content %}
   {% for item in items %}

    <li><a href="#">{{ item }}</li>

  {% endfor %}
{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}
{% block content %}
<p>Add a new topic:</p>
<form action="{% url 'blogs:new_blog' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add topic</button>
</form>

{% endblock content%}